apiVersion: v1
kind: Pod
metadata:
  name: my-configpod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello ${MYVAR}! && sleep 3600']
    env:
        - name: MYVAR
          valueFrom:
            configMapKeyRef:
                name: my-configmap
                key: myKey