apiVersion: v1
kind: Pod
metadata:
  name: containerpod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    ports:
        - containerPort: 8080