apiVersion: v1
kind: Pod
metadata:
  name: my-ns-pod
  namespace: my-ns
  labels:
    env: development
    project: e-c
spec:
  containers:
  - name: namespace-container
    image: busybox
    command: ['sh', '-c', 'sleep 3600']